import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/sidebar/SideBar";
import { NoteProvider } from "@/context/Notes/NoteState";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/context/theme/ThemeState";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nowted",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <NoteProvider>
            <div
              className={`w-full bg-background overflow-hidden h-screen dark:text-white flex  text-blue`}
            >
              <div className="w-[18%]">
                <SideBar />
              </div>
              <div className="overflow-y-auto w-[82%]">{children}</div>
              <Toaster position="bottom-right" />
            </div>
          </NoteProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
